# -*- coding: utf-8 -*-
"""SupervisedML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNm4evoTXhCtkeuKMESSgKdBsHsk7aTE
"""

# Importing packages and classes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Creating Arrays:
x = np.arange(20).reshape(-1, 1)
y = np.array([4, 10, 11, 15, 20, 25, 23, 30, 41, 44, 54,62, 67, 74, 80, 84, 88, 98, 99, 105])
x

y

# creating test set
x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size=8, random_state=0)

# Using train dataset to fit the model
model = LinearRegression().fit(x_train, y_train)
print('Intercept: ',model.intercept_)
print('Slope: ',model.coef_)

# Checking the goodness of fit:
model.score(x_train, y_train)

model.score(x_test, y_test)